components = ["identical", "kani", "pbt", "difffuzz"]

[kani]
harness_path = "kani_harness"
output_path = "kani.tmp"
timeout_secs = 3
gen_harness = true
keep_harness = true
keep_output = true
use_preconditions = true
loop_unwind = 17

[alive2]
alive2_path = ""
output_path = "alive2.tmp"
keep_output = false

[diff_fuzz]
harness_path = "df_harness"
output_path = "df.tmp"
initial_inputs = 16
input_len = 140000
executions = 100000
gen_harness = true
keep_harness = true
keep_output = true
catch_panic = false
use_preconditions = true
harness_log = true
pre_fuzz_cmd = "cp df_harness.rs df_harness/src/main.rs"

[pbt]
harness_path = "pbt_harness"
output_path = "pbt.tmp"
test_cases = 2000
timeout_secs = 120
gen_harness = true
keep_harness = true
keep_output = true
use_preconditions = true
